receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
    send_batch_max_size: 10
    send_batch_size: 5
    timeout: 1s

exporters:
  prometheus:
    endpoint: 0.0.0.0:8890
    namespace: kip-714
    resource_to_telemetry_conversion:
      enabled: true

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]